name: dash_tools
description: A Very Good Project created by Very Good CLI.
version: 0.0.2+2
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
#  SDK
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  code_text_field: ^1.1.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  yaru_widgets: ^3.1.0
  yaru: ^1.1.0
  yaru_icons: ^2.2.1
  window_manager: ^0.3.6
  handy_window: ^0.3.1
  flutter_riverpod: ^2.4.0
  equatable: ^2.0.5
  super_editor: ^0.2.6
  super_clipboard: ^0.6.4
  dart_jsonwebtoken: ^2.11.0

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
